# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelHeros' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelHeros

  target 'MarvelHerosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelHerosUITests' do
    # Pods for testing
  end

end
